config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root    'sessions#new'
  get     'new_user'      => 'users#new'
  post    'login'         => 'sessions#create'
  delete  'logout'        => 'sessions#destroy'
  get     'flip_plug'     => 'plugs#flip_plug'
  get     'modals/:id'    => 'modals#show'
  resources :plugs
  resources :users

  match "*path", to: "status_redirect#not_found", via: :all

end

app/models/user.rb
class User < ActiveRecord::Base
    before_save     :before_save_user
    after_create    :after_create_user
    
    has_many :rooms, dependent: :destroy
    has_many :plugs, dependent: :destroy
    
    validates :name, presence: true
    validates :email, presence: true,
                      uniqueness: { case_sensitive: false }
    validates :password, presence: true, 
                         length: { minimum: 6 }
    has_secure_password
    
    def find_and_auth_user(username, password)
        username.downcase!
        
        user = User.find_by(email: username)
        auth = false
        
        # If you found the user, attempt to authenticate
        if user
            auth = user.authenticate(password)
        end
        
        # If there are errors, set them. Otherwise, set id on self
        if !user
            self.errors.add :email, username + ' not found'
        elsif !auth
            self.errors.add :password
        else
            self.id = user.id
        end
    end
    
    
    ############################### Private #############################    
    
    private
        def before_save_user
            clean_email
        end
        
        def after_create_user
            # if you're creating a new user, create the default room 'Your plugs'
            self.rooms.create(name: "Your Plugs")
        end
        
        def clean_email
            # downcase the whole email
            self.email = self.email.downcase
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]

    def show
        # Prevent the user from routing to anywhere but their user
        @user = User.find(@current_user.id)
        @rooms = @user.rooms.order(created_at: :asc)
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params);
        if @user.save
            # redirect_to uses RESTful routing. When provided a specific object
            # it goes to that object's 'show' action
            
            # log in the user
            log_in(@user)
            
            # the user_url with argument @user builds out the url to that resource
            # https://home-connect-mstephenhunt.c9users.io/users/5
            redirect_to user_url(@user)
        else
            render 'new'
        end
    end
    
    private
    
        def user_params
           params.require(:user).permit(:name, :email, :password, :password_confirmation) 
        end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', obj: @user%>
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
    
    <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<%# app/views/user/show.html.erb %>

<div class="container">
  <%= render "shared/header" %>
</div>
<div class="container">
  <%# Render each of the user's rooms with its plugs %>
  <% @rooms.each do |room| %>
    <section class="room">
      <h2 class="room-title"><%= room.name %></h2>
      <% room.plugs.each_slice(2) do |p1, p2| %>
        <div class="row">
        <%# If there are two, show two %>
        <% if !p2.nil? %>
          <%= render p1 %>
          <%= render p2 %>
        <%# Otherwise, just show the one %>
        <% else %>
          <%= render p1 %>
        <% end %>
        </div>
      <% end %>
    </section>
  <% end %> <%# end @rooms.each %>
  
  <div id="myModal"></div>
  <%= link_to "Add plug", new_plug_path %>
</div>