config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root    'sessions#new'
  get     'new_user'      => 'users#new'
  post    'login'         => 'sessions#create'
  delete  'logout'        => 'sessions#destroy'
  get     'flip_plug'     => 'plugs#flip_plug'
  get     'modals/:id'    => 'modals#show'
  resources :plugs
  resources :users

  match "*path", to: "status_redirect#not_found", via: :all

end

app/views/shared/_error_messages.html.erb
<%# obj is generic object passed into this form to show error messages %>
<% if !obj.nil? && obj.errors.any? %>
<div>
    <p><%= "Error".pluralize(obj.errors.count) %>:</p>
    <ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<%# app/views/shared/_header.html.erb %>
<nav class="navbar navbar-default navbar-static-top">
    <div class="navbar-header">
        <%= link_to image_tag("spudtronics.png", alt: "Spudtronics", :id => "menu_logo"), "/" %>
    </div>
    <ul class="nav navbar-nav">
        <li class="hide-mobile menu-li">
            <div>
                <%= link_to "/", class: "btn btn-default no-border-btn" do %>
                    <span><%= @current_user.name %></span>
                <% end %>
            </div>
        </li>
        <li class="menu-li">
            <div>
                <%= link_to logout_path, method: :delete, class: "btn btn-default no-border-btn" do %>
                    <span>Log out</span><span class="glyphicon glyphicon-log-out" aria-hidden="true" id="log-out-glyph"></span>
                <% end %>
            </div>
        </li>
    </ul>
</nav>