config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root    'sessions#new'
  get     'new_user'      => 'users#new'
  post    'login'         => 'sessions#create'
  delete  'logout'        => 'sessions#destroy'
  get     'flip_plug'     => 'plugs#flip_plug'
  get     'modals/:id'    => 'modals#show'
  resources :plugs
  resources :users

  match "*path", to: "status_redirect#not_found", via: :all

end

app/models/plug.rb
# app/models/plug.rb
class Plug < ActiveRecord::Base
  belongs_to          :user
  belongs_to          :room
  
  # Can get this attribute from the edit_plug modal where we can create a room
  # from a plug
  attr_accessor       :new_room_name
  
  before_validation   :before_validation
  
  validates :name,    presence: true
  validates :feed_id, presence: true               
  validates :state,   presence: true, inclusion: { in: %w(ON OFF ERR) }
  validates :user_id, presence: true
  validates :user,    presence: true
  validates :room_id, presence: true
  validates :room,    presence: true

  # returns a hash with params [:error] and [:state]
  def get_state
    if self.feed_id.nil?
      return { state: nil, error: "Error: no feed provided" }
    end
    
    # call integration class to get plug's state
    state = PlugExtIntegration.get_state(self.feed_id)
    
    # if somehow you didn't get a state or an error, mark there being a problem
    if state[:error].nil? && state[:state].nil?
      return { state: nil, error: "Error finding state" }
    end
    
    return state
  end
  
  
  def flip_plug
    # whatever the state is, flip it
    flipped_state = flip_state(self.state)
    
    # write out that state change to adafruit
    write_out = PlugExtIntegration.set_state(self.feed_id, flipped_state)
    
    # if an error has been returned, return the error hash
    if (defined? write_out[:error])
      puts "ERROR in writing to Adafruit: #{write_out[:error]}"
      return write_out
    end
    
    # Save the state change on this plug, save it locally
    self.state = flipped_state
    self.save
  end
  
  
  private

    def before_validation
      clean_state
      set_user_or_room
    end
    
    def clean_state
      # if the plug's state isn't valid, attempt to go out and find it
      if self.state != "ON" || self.state != "OFF" || self.state != "ERR"
        ret_state = self.get_state
        
        # if you got a state back, set it on the plug. Otherwise set ERR
        if(!ret_state[:state].nil?)
          self.state = ret_state[:state]
        else
          self.state = "ERR"
        end
      end
      
      # If plug state is undefined, default to ERR
      if self.state.nil?
        self.state == "ERR"
      end
    end
    
    def set_user_or_room
      # if this is being created without a room or a user, 
      # default it to 'Your plugs' room and/or set user_id
      
      # can't recover from this
      if self.room.nil? && self.user_id.nil? 
        return
      end
      
      # no room id, set to 'Your Plugs'
      if self.room.nil?
        self.room = self.user.rooms.find_by(name: "Your Plugs")
      # no user, set from the room you're in
      elsif self.user.nil?
        self.user = self.room.user
      end
    end

    def flip_state(state)
      if state == "ON"
        return "OFF"
      elsif state == "OFF"
        return "ON"
      else
        return "OFF"
      end
    end
end

app/models/plug/plug_ext_integration.rb
require 'adafruit/io'

# Current implementation uses adafruit as mqtt broker
class Plug 
    class PlugExtIntegration
        # Returns :state => "state", :error => "error message"
        def self.get_state(feed_id)
            aio = get_aio
            feed = aio.feeds.retrieve(feed_id)
            
            # If there's a specific error from Adafruit, return that
            if(defined? feed.error)
                return :state => nil, :error => feed.error
            # If feed.id id def'd, means you read the feed
            elsif(defined? feed.id)
                return :state => feed.last_value, :error => nil
            # no feed error and no feed id? Catch all...
            else
                return :state => nil, :error => "Generic error"
            end
        end
        
        # Returns true if good, :error if no good
        def self.set_state(feed_id, state)
            begin
                aio = get_aio
                feed = aio.feeds.retrieve(feed_id)
                
                if(defined? feed.error)
                    return :error => feed.error
                end
                
                data = aio.feeds(feed_id).data.last
                data.value = state
                data.save
            rescue Exception => e
                return :error => "Adafruit threw exception: #{e}"
            end
        end
        
        private
            def self.get_aio
                aio = Adafruit::IO::Client.new :key => ENV["ADAFRUIT_API_KEY"]
            end
    end
end

app/controllers/plugs_controller.rb
class PlugsController < ApplicationController
    
    def new
        @plug = @current_user.plugs.new
    end
    
    def create
        @plug = @current_user.plugs.new(plug_params)
        if @plug.save
            redirect_to @current_user
        else
            render 'new'
        end
    end
    
    def edit
        @plug = Plug.find(params[:id])
    end
    
    def update
        # If the user has provided a new room, create that new room and associate
        # this plug with that room
        if params[:plug][:new_room_name] != ""
            room = current_user.rooms.create(name: params[:plug][:new_room_name])
            params[:plug][:room_id] = room.id
        end
        
        # Update the plug
        @plug = Plug.find(params[:id])
        if @plug.update_attributes(plug_params)
            redirect_to current_user
        else
            render 'edit'
        end
    end
    
    def destroy
        Plug.find(params[:id]).destroy
        redirect_to current_user
    end
    
    def flip_plug
        plug = Plug.find(params[:format])
        plug.flip_plug
        redirect_to current_user
    end
    
    private
        def plug_params
            params.require(:plug).permit(:name, :user_id, :feed_id, :room_id, :new_room_name)
        end
end

app/helpers/plugs_helper.rb
module PlugsHelper
end

app/views/plugs/_delete_plug.html.erb
<%# app/views/plugs/_delete_plug.html.erb %>

<div class="modal-footer">
    <%= link_to object, method: :delete, class: "btn button-save" do %>
        <span class="glyphicon glyphicon-ok" aria-hidden="true">
    <% end %>
    <button type="button" class="btn button-cancel" data-dismiss="modal">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
    </button>
</div>

app/views/plugs/_edit_plug.html.erb
<%# app/views/plugs/_edit_plug.html.erb %>

<%= form_for(object, :html => { :class => "form-horizontal" }) do |o| %>
    <div class="modal-form-group form-group">
        <!--Plug name-->
        <div class="col-xs-3">
            <%= o.label :name, class: "modal-label control-label" %>
        </div>
        <div class="col-xs-9">
            <span class="form-row-glyphicon glyphicon glyphicon-tag" aria-hidden="true"></span>
            <%= o.text_field :name, class: "modal-form form-control" %>
        </div>
    </div>
    
    <!--Feed ID-->
    <div class="modal-form-group form-group">
        <div class="col-xs-3">
            <%= o.label :feed_id, class: "modal-label control-label" %>
        </div>
        <div class="col-xs-9">
            <span class="form-row-glyphicon glyphicon glyphicon-link" aria-hidden="true"></span>
            <%= o.text_field :feed_id, class: "modal-form form-control" %>     
        </div>
    </div>
    
    <!--Room Selection-->
    <div class="modal-form-group form-group">
        <div class="col-xs-3">
            <%= o.label :room_id, class: "modal-label control-label" %>
        </div>
        <div class="col-xs-9">
            <div class="dropdown">
                <button class="btn btn-default dropdown-toggle dropdown modal-dropdown" type="button" id="edit-plug-room-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span class="dropdown-label" id="current-room-name"><%= form_data[:current_room_name] %></span>
                    <span class="caret dropdown-caret"></span>
                    <%# Hidden field used to hold the current room id %>
                    <%= o.text_field :room_id, id: "plug-room-id", class: "default-hide" %>
                </button>
                <ul class="modal-dropdown dropdown-menu" aria-labelledby="edit-plug-room-dropdown">
                    <% form_data[:rooms].each do |r| %>
                        <li><a class="room-selection" href="#"><%= render r, locals: { :room => r } %></a></li>
                    <% end %>
                    <li role="separator" class="divider"></li>
                    <li><a id="add-room" href="#">Add room</a></li>
                </ul>
            </div> 
        </div>
    </div>

    <!--New Room Partial-->
    <%= render partial: "rooms/new", locals: { new_room: o } %>
    
    <div class="modal-footer">
        <%= button_tag(type: 'submit', class: "btn button-save", id: "modal-submit") do %>
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        <% end %>
        <button type="button" class="btn button-cancel" data-dismiss="modal">
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        </button>
    </div>
<% end %>

app/views/plugs/_plug.html.erb
<%# shared/_plug.html.erb %>

<%# set the button style for this row %>
<% if plug.state == "OFF" %>
    <% @class = "plug-toggle-off" %>
<% elsif plug.state == "ON" %>
    <% @class = "plug-toggle-on" %>
<% end %>

<div class="col-md-4">
    <div class="plug-row">
        <ul class="plug-settings">
            <li class="dropdown">
                <a href="#" class="settings-icon dropdown-toggle" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-plug">
                    <% modal_id = "edit-plug-" + plug.id.to_s %>
                    <li>
                        <%= link_to :controller => :modals, 
                                    :action => :show,
                                    :modal => "modal_sm",
                                    :modal_id => modal_id,
                                    :header_glyphicon => "glyphicon-wrench",
                                    :header_title => plug.name,
                                    :form_partial => "plugs/edit_plug",
                                    :object_type => "Plug",
                                    :object_id => plug.id,
                                    :room_id => plug.room_id,
                                    :remote => true,
                                    class: "dropdown-entry", 
                                    'data-toggle': 'modal', 
                                    'data-target': "#" + modal_id do %>
                            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                            <span>Edit</span>
                        <% end %>
                    </li>
                    <li><%= link_to :controller => :modals,
                                    :action => "show",
                                    :modal => "modal_sm",
                                    :modal_id => modal_id,
                                    :header_glyphicon => "glyphicon-trash",
                                    :header_title => "Delete?",
                                    :form_partial => "plugs/delete_plug",
                                    :object_type => "Plug",
                                    :object_id => plug.id,
                                    :remote => true, 
                                    class: "dropdown-entry",
                                    'data-toggle': 'modal',
                                    'data-target': "#" + modal_id do %>
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            <span>Delete</span>
                        <% end %>
                    </li>
                </ul>
            </li>
        </ul>
        <%= link_to flip_plug_path(plug), class: "btn btn-default no-border-btn plug-toggle-button" do %>
            <span class="<%= @class %> glyphicon glyphicon-off plug-toggle-button-inner" aria-hidden="true"></span>
            <h3 class="plug-row-name"><%= plug.name %></h3>
        <% end %>
        </div>
</div>

app/views/plugs/edit.html.erb
<h1>Create Plug</h1>
<%= form_for(@plug) do |p| %>
    <%= render 'shared/error_messages', obj: @plug %>

    <%= p.label :name %>
    <%= p.text_field :name %>
    
    <%= p.label :feed_id %>
    <%= p.text_field :feed_id %>
    
    <%= p.submit "Save changes" %>
<% end %>

app/views/plugs/new.html.erb
<h1>Create Plug</h1>
<%= form_for(@plug) do |p| %>
    <%= render 'shared/error_messages', obj: @plug %>

    <%= p.label :name %>
    <%= p.text_field :name %>
    
    <%= p.submit "Create plug" %>
<% end %>